bubblejail.spec: Varied cleanup
This change does a few things:

*   Updates the license to the more specific "GPL-3.0-only" designation.
*   Fixes an `rpmlint` complaint that `%{_libdir}` is present in a
    comment.
*   Isolates common build-time- and runtime-required packages into a
    dedicated `%global`.
*   Breaks out each `BuildRequires` and `Requires` package into a
    dedicated statement.
*   Moves a bunch of packages into the common-required variable. These
    were sniffed out by iterating on COPR builds and examining what
    breaks each time. It turns out documentation generation requires a
    number of ostensibly runtime-required packages.

Appendix: an example of a COPR build failure during doc generation:

[3/8] /usr/bin/meson --internal exe --unpickle ...
FAILED: docs/bubblejail.1.md
/usr/bin/meson --internal exe --unpickle ...
while executing ['/usr/bin/python3', '-O', ...
--- stderr ---
Traceback (most recent call last):
  [snip]
    from .bubblejail_seccomp import SeccompState
  File "/builddir/build/BUILD/bubblejail-0.7.0/redhat-linux-build/src/bubblejail/bubblejail_seccomp.py", line 42, in <module>
    seccomp_init = import_from_cdll('seccomp_init', (c_uint, ), c_void_p)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/bubblejail-0.7.0/redhat-linux-build/src/bubblejail/bubblejail_seccomp.py", line 36, in import_from_cdll
    c_function = getattr(libseccomp, func_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: /usr/bin/python3: undefined symbol: seccomp_init